# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit722part3task.azurecr.io/book_catalog:v1
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          value: "postgresql://sit722_part3_95rm_user:0WbHbMWbPW5euXLfHk0mdPu5Ah5Fh7az@dpg-crip7k3v2p9s738m55hg-a.oregon-postgres.render.com/sit722_part3_95rm"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: book-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sit722part3task.azurecr.io/inventory_management:v1
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          value: "postgresql://sit722_part3_95rm_user:0WbHbMWbPW5euXLfHk0mdPu5Ah5Fh7az@dpg-crip7k3v2p9s738m55hg-a.oregon-postgres.render.com/sit722_part3_95rm"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: inventory-management
