# Your Solution
version: '3.8'
 
services:
  # Book Catalog Service
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://sit722_part3_95rm_user:0WbHbMWbPW5euXLfHk0mdPu5Ah5Fh7az@dpg-crip7k3v2p9s738m55hg-a.oregon-postgres.render.com/sit722_part3_95rm
 
  # Inventory Management Service
  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://sit722_part3_95rm_user:0WbHbMWbPW5euXLfHk0mdPu5Ah5Fh7az@dpg-crip7k3v2p9s738m55hg-a.oregon-postgres.render.com/sit722_part3_95rm
